//
//  UpdateFactorPayload.swift
//  TwilioVerify
//
//  Created by Sergio Fierro on 6/2/20.
//  Copyright © 2020 Twilio. All rights reserved.
//

import Foundation

///Describes the information required to update a **Factor**
public protocol UpdateFactorPayload {
  ///Factor Sid
  var sid: String { get }
}

///Describes the information required to update a **Factor** which type is **Push**
public struct UpdatePushFactorPayload: UpdateFactorPayload {
  ///Factor Sid
  public let sid: String
  ///Registration token generated by APNS when registering for remote notifications
  public let pushToken: String
  
  /**
  Creates an **UpdatePushFactorPayload** with the given parameters
  - Parameters:
    - sid: Factor Sid
    - pushToken: Registration token generated by APNS when registering for remote notifications
  */
  public init(sid: String, pushToken: String) {
    self.sid = sid
    self.pushToken = pushToken
  }
}
