# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane

output_directory = './fastlane/Test Output/'
coverage_directory = '/coverage'
complete_suite = 'CompleteSuite'
single_ftl_device = [{ios_model_id: 'iphone11pro', ios_version_id: '13.3'}]
all_ftl_devices = [
  {ios_model_id: 'iphone11pro', ios_version_id: '13.6'},
  {ios_model_id: 'iphonexs', ios_version_id: '12.3'},
  {ios_model_id: 'iphone8', ios_version_id: '11.4'}
]

default_platform(:ios)

platform :ios do
  desc "Runs the tests"
  lane :test do |options|
    test_plan = options[:test_plan]
    ftl_devices = single_ftl_device
    
    if options[:ftl_devices] == 'all'
      ftl_devices = all_ftl_devices
    end
  
    scan(
      scheme: "TwilioVerify",
      testplan: test_plan,
      workspace: "TwilioVerify.xcworkspace",
      device: "iPhone 11",
      reset_simulator: true,
      code_coverage: true,
      suppress_xcode_output: true,
      output_types: 'junit,html',
      output_files: 'junit.xml, report.html',
      output_directory: output_directory + test_plan,
      should_zip_build_products: test_plan != complete_suite
    )

    if test_plan == complete_suite
      slather(
        circleci: true,
        use_bundle_exec: true,
        output_directory: output_directory + test_plan + coverage_directory,
        scheme: "TwilioVerify",
        workspace: "TwilioVerify.xcworkspace",
        proj: "TwilioVerify.xcodeproj",
        html: true,
        verbose: false
      )
    else
      firebase_test_lab_ios_xctest(
        gcp_project: 'twilio-firebase-266721',
        timeout_sec: 300,
        devices: [
          {
            ios_model_id: 'iphone11pro',       
            ios_version_id: '13.3'
          }
        ]
      )
    end
  end

  lane :build_universal_framework do
    build_app(
      silent: true,
      clean: false,
      scheme: "TwilioVerifySDK",
      workspace: "TwilioVerify.xcworkspace",
      skip_codesigning: true,
      skip_archive: true
    )
  end
end
